Repository 2TEAM-Ideality/be14-4th-Ideality-MyLocalDiary-front, pull requests merged in 2025-05, with the labels that each got.

#62 [FEAT] 팔로우시 알람이 실시간으로 전송
  my-local-diary/src/components/common/NotificationPopup.vue
  my-local-diary/src/components/common/SSEconnect.vue
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/search/SearchUserModal.vue
  my-local-diary/src/main.js
  my-local-diary/src/stores/notificationStore.js
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/mypage/Mypage.vue
Labels: ✨ Feature

#64 [FEAT] 다른 유저 페이지 이동 시 상태 처리
  my-local-diary/public/json/db.json
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/common/userprofile.vue
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/mypage/Mypage.vue
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#65 [대기] 팔로우알림 실시간성 더 확보, 비공개계정의 수락/거절 추가
  my-local-diary/src/components/common/NotificationPopup.vue
Labels: ✨ Feature

#67 [FEAT] 회원 로그인, 로그아웃, 토큰 재발급 연동 완료
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/main.js
  my-local-diary/src/router/index.js
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/Landingpage.vue
Labels: ✨ Feature

#69 [FEAT] 지도& 유저 백엔드 연결
  my-local-diary/src/assets/profile/default.png
  my-local-diary/src/components/mypage/MiniMap.vue
  my-local-diary/src/components/mypage/TodayDiary.vue
  my-local-diary/src/components/mypage/UserProfileModal.vue
  my-local-diary/src/components/post/MenuToggle.vue
  my-local-diary/src/components/post/PostCard.vue
  my-local-diary/src/components/post/PostCommentCard.vue
  my-local-diary/src/components/post/PostCreate.vue
  my-local-diary/src/components/post/PostPhoto.vue
  my-local-diary/src/components/report/ReportModal.vue
  my-local-diary/src/router/index.js
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/CreateDiary.vue
  my-local-diary/src/views/Landingpage.vue
  my-local-diary/src/views/MapHome.vue
  my-local-diary/src/views/Stamppage.vue
  my-local-diary/src/views/UserMapView.vue
  my-local-diary/src/views/mypage/Mypage.vue
Labels: ✨ Feature

#72 fix postCreate 고침
  my-local-diary/src/components/auth/AuthModal.vue
  my-local-diary/src/components/post/PostCreate.vue
Labels: 🐞 BugFix

#75 fix 충돌 찐 해결
  my-local-diary/src/components/post/PostCreate.vue
Labels: 🐞 BugFix

#78 Feature/post back likes
  my-local-diary/src/components/mypage/Temp.vue
  my-local-diary/src/components/post/PostCard.vue
  my-local-diary/src/components/post/PostCommentCard.vue
  my-local-diary/src/views/mypage/Mypage.vue
Labels: ✨ Feature

#84 [REFACOR] localStorage 다시 도입
  my-local-diary/src/components/common/userprofile.vue
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/Landingpage.vue
Labels: 🔨 Refactor
