Repository 2TEAM-Ideality/be14-4th-Ideality-MyLocalDiary-front, pull requests merged in 2025-04, with the labels that each got.

#1 [feature] LandingPage 및 사이드바, 라우팅
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/src/App.vue
  my-local-diary/src/assets/Follower.png
  my-local-diary/src/assets/Map.png
  my-local-diary/src/assets/My_Local_Diary.png
  my-local-diary/src/assets/My_Local_Diary_Black.png
  my-local-diary/src/assets/Pen.png
  my-local-diary/src/assets/Search.png
  my-local-diary/src/assets/base.css
  my-local-diary/src/assets/cursor_ 10.svg
  my-local-diary/src/assets/kakao_logo.png
  my-local-diary/src/assets/logo.svg
  my-local-diary/src/assets/main.css
  my-local-diary/src/assets/notifications.png
  my-local-diary/src/assets/person.png
  my-local-diary/src/assets/stamp.png
  my-local-diary/src/assets/꽐라냥.png
  my-local-diary/src/assets/독서냥.png
  my-local-diary/src/assets/맛집냥.png
  my-local-diary/src/assets/산책냥.png
  my-local-diary/src/assets/영화냥.png
  my-local-diary/src/assets/카페냥.png
  my-local-diary/src/components/HelloWorld.vue
  my-local-diary/src/components/TheWelcome.vue
  my-local-diary/src/components/WelcomeItem.vue
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/main.js
  my-local-diary/src/plugins/vuetify.js
  my-local-diary/src/router/index.js
  my-local-diary/src/views/Landingpage.vue
  my-local-diary/src/views/Mypage.vue
Labels: ✨ Feature

#5 Feature/sidebar
  my-local-diary/src/App.vue
  my-local-diary/src/assets/cursor/cursor_ 10.svg
  my-local-diary/src/assets/cursor/슈크림붕어빵1.png
  my-local-diary/src/assets/logo/My_Local_Diary.png
  my-local-diary/src/assets/logo/My_Local_Diary_Black.png
  my-local-diary/src/assets/logo/kakao_logo.png
  my-local-diary/src/assets/sidebar/Follower.png
  my-local-diary/src/assets/sidebar/Map.png
  my-local-diary/src/assets/sidebar/Pen.png
  my-local-diary/src/assets/sidebar/Search.png
  my-local-diary/src/assets/sidebar/notifications.png
  my-local-diary/src/assets/sidebar/person.png
  my-local-diary/src/assets/sidebar/stamp.png
  my-local-diary/src/assets/stamp_pic/cat_bar.png
  my-local-diary/src/assets/stamp_pic/꽐라냥.png
  my-local-diary/src/assets/stamp_pic/독서냥.png
  my-local-diary/src/assets/stamp_pic/맛집냥.png
  my-local-diary/src/assets/stamp_pic/산책냥.png
  my-local-diary/src/assets/stamp_pic/영화냥.png
  my-local-diary/src/assets/stamp_pic/카페냥.png
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/icons/IconCommunity.vue
  my-local-diary/src/components/icons/IconDocumentation.vue
  my-local-diary/src/components/icons/IconEcosystem.vue
  my-local-diary/src/components/icons/IconSupport.vue
  my-local-diary/src/components/icons/IconTooling.vue
  my-local-diary/src/components/stamp/stamp.vue
  my-local-diary/src/router/index.js
  my-local-diary/src/views/Landingpage.vue
  my-local-diary/src/views/LayOut.vue
  my-local-diary/src/views/MapHome.vue
  my-local-diary/src/views/Mypage.vue
  my-local-diary/src/views/Stamppage.vue
Labels: 🔨 Refactor

#10 Feature/sidebar
  my-local-diary/index.html
  my-local-diary/src/assets/stamp_pic/꽐라냥.png
  my-local-diary/src/assets/stamp_pic/독서냥.png
  my-local-diary/src/assets/stamp_pic/맛집냥.png
  my-local-diary/src/assets/stamp_pic/산책냥.png
  my-local-diary/src/assets/stamp_pic/영화냥.png
  my-local-diary/src/assets/stamp_pic/카페냥.png
  my-local-diary/src/components/stamp/stamp.vue
  my-local-diary/src/router/index.js
  my-local-diary/src/views/Landingpage.vue
  my-local-diary/src/views/Stamppage.vue
Labels: ✨ Feature

#15 [Feature] 지도 검색 가능 여부 확인
  my-local-diary/index.html
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/src/components/map/SearchLoactaion.vue
  my-local-diary/src/components/mypage/MiniMap.vue
  my-local-diary/src/components/mypage/TodayDiary.vue
  my-local-diary/src/components/mypage/UserProfileModal.vue
  my-local-diary/src/main.js
  my-local-diary/src/views/Mypage.vue
Labels: ✨ Feature

#19 [Feature] 로딩 모달창 구현 완료
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/src/components/common/LoadingModal.vue
  my-local-diary/src/components/common/TempLoadingModalParent.vue
  my-local-diary/src/router/index.js
Labels: ✨ Feature

#20 [Feature] 지도 검색 기능 구현 일단 완료
  my-local-diary/.env.example
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/map/SearchLoactaion.vue
  my-local-diary/src/components/map/SearchLocation2.vue
  my-local-diary/src/stores/uiStore.js
  my-local-diary/src/views/MapHome.vue
  my-local-diary/src/views/Mypage.vue
  my-local-diary/vite.config.js
Labels: ✨ Feature

#24 feat: 마커 구현 완료
  my-local-diary/src/components/common/CustomMarker.vue
  my-local-diary/src/data/places.js
  my-local-diary/src/router/index.js
  my-local-diary/src/views/TestMarker.vue
Labels: ✨ Feature

#26 [FEAT] json-server 작업 완료
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/public/images/profile/profile.png
  my-local-diary/public/images/stamp_pic/cat_bar.png
  my-local-diary/public/images/stamp_pic/꽐라냥.png
  my-local-diary/public/images/stamp_pic/독서냥.png
  my-local-diary/public/images/stamp_pic/맛집냥.png
  my-local-diary/public/images/stamp_pic/산책냥.png
  my-local-diary/public/images/stamp_pic/영화냥.png
  my-local-diary/public/images/stamp_pic/카페냥.png
  my-local-diary/src/json/db.json
  my-local-diary/src/views/UserMapView.vue
  package-lock.json
Labels: ✨ Feature, 📬 API

#21 Feature/sidebar ( pr 내용 수정 완)
  my-local-diary/db.json
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/src/assets/profile/idol_profile.png
  my-local-diary/src/components/common/userprofile.vue
  my-local-diary/src/components/stamp/stamp.vue
  my-local-diary/src/router/index.js
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/Stamppage.vue
Labels: ✨ Feature

#28 Feature/post 게시글 작성 페이지 구현
  .idea/.gitignore
  .idea/MyLocalDiary_Front.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/src/App.vue
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/map/SearchLocation.vue
  my-local-diary/src/components/map/SearchLocation2.vue
  my-local-diary/src/components/post/PostCreate.vue
  my-local-diary/src/main.js
  my-local-diary/src/router/index.js
  my-local-diary/src/views/Mypage.vue
  my-local-diary/vite.config.js
Labels: ✨ Feature

#30 Feature/marker 구현 완료
  my-local-diary/src/components/common/CustomMarker.vue
  my-local-diary/src/views/TestMarker.vue
Labels: ✨ Feature

#31 Feature/sw/post 게시글 모달 창 구현
  my-local-diary/src/assets/icons/fish_default.png
  my-local-diary/src/assets/icons/fish_liked.png
  my-local-diary/src/components/post/PostAuthorCard.vue
  my-local-diary/src/components/post/PostCard.vue
  my-local-diary/src/components/post/PostCommentCard.vue
  my-local-diary/src/components/post/PostCommentInput.vue
  my-local-diary/src/components/post/PostContentCard.vue
  my-local-diary/src/components/post/PostLikeIcon.vue
  my-local-diary/src/components/post/PostPhoto.vue
  my-local-diary/src/views/TestMarker.vue
Labels: ✨ Feature

#38 [FEAT] 회원가입 모달 구현
  .idea/workspace.xml
  my-local-diary/src/components/auth/AuthModal.vue
  my-local-diary/src/views/Landingpage.vue
Labels: ✨ Feature

#40 [feat] 관리자-신고페이지 구현 완료
  my-local-diary/public/json/db.json
  my-local-diary/src/router/index.js
  my-local-diary/src/views/ReportManagement.vue
Labels: ✨ Feature

#43 feath: 마이페이지
  my-local-diary/src/components/mypage/Temp.vue
  my-local-diary/src/components/mypage/TodayDiary.vue
  my-local-diary/src/views/mypage/Mypage.vue
Labels: ✨ Feature

#45 [FEAT] 더보기 버튼 및 마이페이지 게시글 목록 구현
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/src/components/mypage/PostList.vue
  my-local-diary/src/components/mypage/PostListCard.vue
  my-local-diary/src/components/mypage/Temp.vue
  my-local-diary/src/components/post/MenuToggle.vue
  my-local-diary/src/components/post/PostAuthorCard.vue
  my-local-diary/src/components/post/PostCard.vue
  my-local-diary/src/components/post/PostCommentCard.vue
  my-local-diary/src/components/post/PostContentCard.vue
  my-local-diary/src/components/post/PostPhoto.vue
  my-local-diary/src/views/TestMarker.vue
Labels: ✨ Feature

#48 [Feature] 관리자 페이지 추가 구현
  my-local-diary/package-lock.json
  my-local-diary/package.json
  my-local-diary/public/json/db.json
  my-local-diary/src/components/common/LoadingModal.vue
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/common/TempLoadingModalParent.vue
  my-local-diary/src/components/common/userprofile.vue
  my-local-diary/src/components/map/SearchLocation2.vue
  my-local-diary/src/components/mypage/EditAccount.vue
  my-local-diary/src/components/mypage/EditProfile.vue
  my-local-diary/src/components/mypage/MiniMap.vue
  my-local-diary/src/components/post/PostCard.vue
  my-local-diary/src/router/index.js
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/MapHome.vue
  my-local-diary/src/views/Mypage.vue
  my-local-diary/src/views/ReportManagement.vue
  my-local-diary/src/views/Stamppage.vue
  my-local-diary/src/views/TestMarker.vue
  my-local-diary/src/views/admin/AdminMyPage.vue
  my-local-diary/src/views/admin/RegulationHistory.vue
  my-local-diary/src/views/admin/ReportManagement.vue
  my-local-diary/src/views/mypage/EditPage.vue
  my-local-diary/src/views/mypage/Mypage.vue
  my-local-diary/vite.config.js
Labels: ✨ Feature

#50 feat: 카카오 로그인
  my-local-diary/src/views/Landingpage.vue
Labels: ✨ Feature

#51 hotfix 파일명 변경
  my-local-diary/Dockerfile
  my-local-diary/k8s/frontend-deploy.yml
  my-local-diary/k8s/frontend-svc.yml
  my-local-diary/k8s/ingress.yml
  my-local-diary/nginx.conf
Labels: 🐞 BugFix

#35 [FEAT] 사용자 검색창 및 검색 후 팔로우 버튼 누르기 구현 완료
  my-local-diary/public/json/db.json
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/search/SearchUserModal.vue
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#42 [FEAT] 신고 모달창 작업 완료
  my-local-diary/src/assets/report/report.svg
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/post/MenuToggle.vue
  my-local-diary/src/components/report/ReportModal.vue
  my-local-diary/src/views/UserMapView.vue
  package-lock.json
Labels: ✨ Feature, 🎨 Html&css

#53 sse설정 미리 pr 열어놨습니다.
  my-local-diary/src/App.vue
  my-local-diary/src/components/common/NotificationPopup.vue
  my-local-diary/src/components/common/SSEconnect.vue
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/common/userprofile.vue
  my-local-diary/src/main.js
  my-local-diary/src/router/index.js
  my-local-diary/src/views/Stamppage.vue
  my-local-diary/src/views/mypage/Mypage.vue
Labels: ✨ Feature

#56 [Hotfix] 스탬프 페이지 복원
  my-local-diary/public/json/db.json
  my-local-diary/src/components/auth/AuthModal.vue
  my-local-diary/src/components/mypage/Temp.vue
  my-local-diary/src/components/mypage/TodayDiary.vue
  my-local-diary/src/components/mypage/UserProfileModal.vue
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/Landingpage.vue
  my-local-diary/src/views/Stamppage.vue
  my-local-diary/src/views/admin/RegulationHistory.vue
  my-local-diary/src/views/admin/ReportManagement.vue
  my-local-diary/src/views/mypage/Mypage.vue
  my-local-diary/vite.config.js
Labels: 🐞 BugFix

#61 [Feature]나의 게시글 조회
  my-local-diary/src/components/mypage/Temp.vue
  my-local-diary/src/components/post/PostCard.vue
Labels: ✨ Feature

#59 [Feature] 로그인 / 로그아웃 / 회원 정보 저장 기능 구현
  my-local-diary/src/components/common/Sidebar.vue
  my-local-diary/src/components/common/userprofile.vue
  my-local-diary/src/components/report/ReportModal.vue
  my-local-diary/src/main.js
  my-local-diary/src/router/index.js
  my-local-diary/src/stores/userStore.js
  my-local-diary/src/views/Landingpage.vue
  my-local-diary/src/views/admin/ReportManagement.vue
  my-local-diary/src/views/mypage/Mypage.vue
Labels: ✨ Feature
